- name: codepicnic conf
  template: src=codepicnic.conf dest=/etc/nginx/sites-enabled/codepicnic.conf
  notify:
  - restart nginx 
- name: Add app user 
  action: user name={{ app_user }}
- name: add ubuntu to main group
  user: name={{ deployment_user }} 
        groups={{ app_user }}
        append=yes
- name: docker dir
  file: path=/home/codepicnic/.ssh state=directory mode=700 owner="{{ app_user }}"
- name: key 
  copy: src=key_codepicnic_deploy.id_rsa dest="/home/{{ app_user }}/.ssh/id_rsa" owner="{{ app_user }}" mode=600
- name: clone  
  git: repo=git@github.com:CodePicnic/CodePicnic.git clone=yes version="{{ app_branch }}" dest="/home/{{ app_user }}/app" accept_hostkey=True
  become: yes
  become_user: "{{ app_user }}"
- name: permissions
  file: path="/home/{{ app_user }}/app" owner="{{ deployment_user }}" group="{{ app_user }}" recurse=yes mode=775
- name: upstart workers 
  template: src=workers.conf dest=/etc/init/workers.conf
  notify:
  - restart workers
- name: start workers 
  service: name=workers state=started
