- name: set fact consul_network
  set_fact: swarm_master_ip="{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
  with_items: groups['swarm-master']
- name: Pull from registry
  docker_image:
     name: registry.codepicnic.com:5000/codepicnic/tuna_base
- name: run tuna
  docker_container:
      name: tuna 
      image: registry.codepicnic.com:5000/codepicnic/tuna_master
      state: started
      detach: True
      restart_policy: always
      ports:
      - "80:80"
      env:
          DOCKER_HOST: "{{ swarm_master_ip }}:4000"
