version: '2'
services:
  swarm-agent:
    image: swarm
    container_name: swarm-${NODE_NAME}
    command: join --advertise=${NODE_IP}:2375 consul://${CONSUL_IP}:8500
    network_mode: bridge
    restart: always
  cadvisor:
    image: google/cadvisor:latest
    ports:
    - "3200:8080"
    volumes:
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    container_name: cadvisor-${NODE_NAME}
    network_mode: bridge
    restart: always
  nginx:
    container_name: nginx-${NODE_NAME}
    image: openresty/openresty:trusty 
    restart: always
    ports:
    - "80:80"
    volumes:
    - "/usr/local/openresty/nginx:/usr/local/openresty/nginx"
    - "/usr/local/openresty/nginx-lua:/usr/local/openresty/nginx-lua"
    environment:
    - JWT_SECRET=e7b3b5c7f422a4abdee2bb648224104823e5acd6779c50f9005c7613e168288024e1dc98260e03f29b6558ba8fb0b8b9ba1a9f4a6fad0425c286bdcfbf8b35a1
networks:
  default:
    external:
       name: net-swarm-01
