  - name: apt-key sysdig 
    apt_key: url="https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public" state=present

  - name: Get Sysdig repo 
    get_url: url="http://download.draios.com/stable/deb/draios.list"  dest=/etc/apt/sources.list.d/draios.list mode=0644

  - name: Install Linux Headers
    apt: name="linux-headers-{{ ansible_kernel }}" update_cache=yes

  - name: Install Sysdig 
    apt: name=sysdig update_cache=yes

  - name: /var/log/falco 
    file: path=/var/log/falco state=directory mode=0755

  - name: Install Sysdig Falco 
    apt: name=falco update_cache=yes

  - name: add falco rules 
    copy: src=falco_rules.yaml dest=/etc/falco_rules.yaml

  - name: start falco 
    service: name=falco enabled=yes state=started

