  - name: Gather facts
    action: ec2_facts
  - name: format device
    filesystem: fstype="{{ docker_fs }}" dev="{{ docker_disk }}"
  - name: docker dir
    file: path=/var/lib/docker state=directory
  - name: mount device
    mount: name="/var/lib/docker" src="{{ docker_disk }}" fstype="{{ docker_fs }}" opts=defaults,noatime state=mounted
  - name: apt-get install reqs 
    apt: name=apt-transport-https,ca-certificates,python-pip state=present
  - name: add key
    apt_key: id=58118E89F3A912897C070ADBF76221572C52609D keyserver=hkp://p80.pool.sks-keyservers.net:80
  - name: copy docker repo
    copy: src=docker.list dest=/etc/apt/sources.list.d
  - name: apt-get update
    apt: update_cache=yes
  - name: apt-get purge lxc-docker 
    apt: name=lxc-docker state=absent purge=yes
  - name: apt-cache policy docker-engine 
    shell: apt-cache policy docker-engine 
  - name: apt-get image extra
    apt: name=linux-image-extra-{{ ansible_kernel }},linux-image-extra-virtual state=latest
  - name: modprobe aufs
    modprobe: name=aufs state=present
  - name: modprobe overlayfs 
    modprobe: name=overlayfs state=present
  - name: apt-get apparmor 
    apt: name=apparmor state=latest 
  - name: apt-get install docker 
    #apt: name="docker-engine=1.10.3-0~trusty" state=present
    apt: name=docker-engine state=present
  - name: start docker
    service: name=docker enabled=yes state=started
  - name: add user
    shell: usermod -aG docker ubuntu 
  - name: install docker-py
    pip: name=docker-py
  - name: install docker compose
    get_url: url=https://github.com/docker/compose/releases/download/1.6.2/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755 
