  - name: Gather facts
    action: ec2_facts
#  - name: format device
#    filesystem: fstype=xfs dev="/dev/xvdf"
  - name: docker dir
    file: path=/var/lib/docker state=directory
  - name: mount device
  #mount: name="/var/lib/docker" src="/dev/sdf" fstype=xfs opts=defaults,noatime state=present
    mount: name="/var/lib/docker" src="/dev/xvdf1" fstype=ext4 opts=defaults,noatime state=present
  - name: apt-get install reqs 
    apt: name=apt-transport-https,ca-certificates,python-pip state=present
  - name: add key
    apt_key: id=58118E89F3A912897C070ADBF76221572C52609D keyserver=hkp://p80.pool.sks-keyservers.net:80
  - name: copy docker repo
    copy: src=docker.list dest=/etc/apt/sources.list.d
  - name: apt-get update
    apt: update_cache=yes
  - name: apt-get purge lxc-docker 
    apt: name=lxc-docker state=absent purge=yes
  - name: apt-cache policy docker-engine 
    shell: apt-cache policy docker-engine 
  - name: apt-get image extra
    apt: name=linux-image-extra-{{ ansible_kernel }} state=latest 
  - name: apt-get apparmor 
    apt: name=apparmor state=latest 
  - name: apt-get install docker 
    apt: name=docker-engine state=latest 
  - name: start docker
    service: name=docker enabled=yes state=started
  - name: add user
    shell: usermod -aG docker ubuntu 
  - name: install docker-py
    pip: name=docker-py
  - name: install docker compose
    get_url: url=https://github.com/docker/compose/releases/download/1.6.2/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755 
