- hosts: ansible
  connection: local
  roles:
      - devpad-ec2
- hosts: app 
  pre_tasks:
      - name: register reboot
        stat: path=/var/tmp/reboot.txt
        register: stat_reboot
  roles:
      - base
      - devpad-base  
      - { role: reboot, when: stat_reboot.stat.exists == False }
      - aws-monitoring-scripts
      - sysdig
      - newrelic
      - ruby23
      - passenger
      - devpad-app 
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
 
