  - name: run swarm ami 
    ec2_ami:
      instance_id: "{{ item.id }}"
      name: "{{ new_ami_name }}"
      device_mapping:
      - device_name: /dev/sdb
        size: 500 
        delete_on_termination: false
        volume_type: gp2
      register: swarm_ami
    with_items: "{{ hostvars['127.0.0.1']['var_ec2'].instances }}"
  - name: ami result
    debug: var=swarm_ami.results
